{
  "cells": [
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {
        "id": "VjYy0F2gZIPR",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "68d684f8-5a16-45a9-f95f-40c9dd35605a"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: pygit2==1.15.1 in /usr/local/lib/python3.11/dist-packages (1.15.1)\n",
            "Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from pygit2==1.15.1) (1.17.1)\n",
            "Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.16.0->pygit2==1.15.1) (2.22)\n",
            "/content\n",
            "fatal: destination path 'Fooocus' already exists and is not an empty directory.\n",
            "/content/Fooocus\n",
            "Already up-to-date\n",
            "Update succeeded.\n",
            "[System ARGV] ['entry_with_update.py', '--share', '--always-high-vram']\n",
            "Python 3.11.12 (main, Apr  9 2025, 08:55:54) [GCC 11.4.0]\n",
            "Fooocus version: 2.5.5\n",
            "[Cleanup] Attempting to delete content of temp dir /tmp/fooocus\n",
            "[Cleanup] Cleanup successful\n",
            "Traceback (most recent call last):\n",
            "  File \"/content/Fooocus/entry_with_update.py\", line 46, in <module>\n",
            "    from launch import *\n",
            "  File \"/content/Fooocus/launch.py\", line 152, in <module>\n",
            "    from webui import *\n",
            "  File \"/content/Fooocus/webui.py\", line 10, in <module>\n",
            "    import modules.async_worker as worker\n",
            "  File \"/content/Fooocus/modules/async_worker.py\", line 3, in <module>\n",
            "    from extras.inpaint_mask import generate_mask_from_image, SAMOptions\n",
            "  File \"/content/Fooocus/extras/inpaint_mask.py\", line 6, in <module>\n",
            "    from extras.GroundingDINO.util.inference import default_groundingdino\n",
            "  File \"/content/Fooocus/extras/GroundingDINO/util/inference.py\", line 3, in <module>\n",
            "    import ldm_patched.modules.model_management as model_management\n",
            "  File \"/content/Fooocus/ldm_patched/modules/model_management.py\", line 121, in <module>\n",
            "    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)\n",
            "                                  ^^^^^^^^^^^^^^^^^^\n",
            "  File \"/content/Fooocus/ldm_patched/modules/model_management.py\", line 90, in get_torch_device\n",
            "    return torch.device(torch.cuda.current_device())\n",
            "                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/cuda/__init__.py\", line 971, in current_device\n",
            "    _lazy_init()\n",
            "  File \"/usr/local/lib/python3.11/dist-packages/torch/cuda/__init__.py\", line 319, in _lazy_init\n",
            "    torch._C._cuda_init()\n",
            "RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx\n"
          ]
        }
      ],
      "source": [
        "!pip install pygit2==1.15.1\n",
        "%cd /content\n",
        "!git clone https://github.com/lllyasviel/Fooocus.git\n",
        "%cd /content/Fooocus\n",
        "!python entry_with_update.py --share --always-high-vram\n"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# prompt: {\n",
        "#   \"cells\": [\n",
        "#     {\n",
        "#       \"cell_type\": \"code\",\n",
        "#       \"execution_count\": 2,\n",
        "#       \"metadata\": {\n",
        "#         \"id\": \"VjYy0F2gZIPR\",\n",
        "#         \"outputId\": \"68d684f8-5a16-45a9-f95f-40c9dd35605a\",\n",
        "#         \"colab\": {\n",
        "#           \"base_uri\": \"https://localhost:8080/\"\n",
        "#         }\n",
        "#       },\n",
        "#       \"outputs\": [\n",
        "#         {\n",
        "#           \"output_type\": \"stream\",\n",
        "#           \"name\": \"stdout\",\n",
        "#           \"text\": [\n",
        "#             \"Requirement already satisfied: pygit2==1.15.1 in /usr/local/lib/python3.11/dist-packages (1.15.1)\\n\",\n",
        "#             \"Requirement already satisfied: cffi>=1.16.0 in /usr/local/lib/python3.11/dist-packages (from pygit2==1.15.1) (1.17.1)\\n\",\n",
        "#             \"Requirement already satisfied: pycparser in /usr/local/lib/python3.11/dist-packages (from cffi>=1.16.0->pygit2==1.15.1) (2.22)\\n\",\n",
        "#             \"/content\\n\",\n",
        "#             \"fatal: destination path 'Fooocus' already exists and is not an empty directory.\\n\",\n",
        "#             \"/content/Fooocus\\n\",\n",
        "#             \"Already up-to-date\\n\",\n",
        "#             \"Update succeeded.\\n\",\n",
        "#             \"[System ARGV] ['entry_with_update.py', '--share', '--always-high-vram']\\n\",\n",
        "#             \"Python 3.11.12 (main, Apr  9 2025, 08:55:54) [GCC 11.4.0]\\n\",\n",
        "#             \"Fooocus version: 2.5.5\\n\",\n",
        "#             \"[Cleanup] Attempting to delete content of temp dir /tmp/fooocus\\n\",\n",
        "#             \"[Cleanup] Cleanup successful\\n\",\n",
        "#             \"Traceback (most recent call last):\\n\",\n",
        "#             \"  File \\\"/content/Fooocus/entry_with_update.py\\\", line 46, in <module>\\n\",\n",
        "#             \"    from launch import *\\n\",\n",
        "#             \"  File \\\"/content/Fooocus/launch.py\\\", line 152, in <module>\\n\",\n",
        "#             \"    from webui import *\\n\",\n",
        "#             \"  File \\\"/content/Fooocus/webui.py\\\", line 10, in <module>\\n\",\n",
        "#             \"    import modules.async_worker as worker\\n\",\n",
        "#             \"  File \\\"/content/Fooocus/modules/async_worker.py\\\", line 3, in <module>\\n\",\n",
        "#             \"    from extras.inpaint_mask import generate_mask_from_image, SAMOptions\\n\",\n",
        "#             \"  File \\\"/content/Fooocus/extras/i\n",
        "\n",
        "npaint_mask.py\\\", line 5, in <module>\\n\",\n",
        "            \"    import modules.shared as shared\\n\",\n",
        "            \"ModuleNotFoundError: No module named 'modules.shared'\\n\"\n",
        "          ]\n",
        "        },\n",
        "        {\n",
        "          \"output_type\": \"error\",\n",
        "          \"ename\": \"ModuleNotFoundError\",\n",
        "          \"evalue\": \"No module named 'modules.shared'\",\n",
        "          \"traceback\": [\n",
        "            \"\\n\",\n",
        "            \"---------------------------------------------------------------------------\\n\",\n",
        "            \"ModuleNotFoundError                       Traceback (most recent call last)\\n\",\n",
        "            \"/usr/local/lib/python3.11/dist-packages/IPython/core/interactiveshell.py in run_code(self, code_obj, result, **kw)\\n\",\n",
        "            \"   1477             self.showtraceback(running_compiled_code, \\n\",\n",
        "            \"   1478                             tb_offset=tb_offset,\\n\",\n",
        "            \"-> 1479                             exception_only=exception_only)\\n\",\n",
        "            \"   1480         else:\\n\",\n",
        "            \"   1481             if exception_only and not (isinstance(e, SyntaxError) and not e.text):\\n\",\n",
        "            \"\\n\",\n",
        "            \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py in showtraceback(self, *args, **kwargs)\\n\",\n",
        "            \"    1013         if tb_offset:\\n\",\n",
        "            \"    1014             self.tb_offset = tb_offset\\n\",\n",
        "            \"-> 1015         return VerboseTB.showtraceback(self, *args, **kwargs)\\n\",\n",
        "            \"    1016 \\n\",\n",
        "            \"    1017     def showsyntaxerror(self, filename=None, tb_offset=None, **kwargs):\\n\",\n",
        "            \"\\n\",\n",
        "            \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py in showtraceback(self, exc_tuple, filename, tb_offset, exception_only, running_compiled_code)\\n\",\n",
        "            \"    875         if running_compiled_code:\\n\",\n",
        "            \"    876             # For an exception thrown during compilation, print the line number\\n\",\n",
        "            \"--> 877             self.print_exception(*exc_tuple)\\n\",\n",
        "            \"    878             return\\n\",\n",
        "            \"    879         \\n\",\n",
        "            \"\\n\",\n",
        "            \"/usr/local/lib/python3.11/dist-packages/IPython/core/ultratb.py in print_exception(self, etype, value, tb, tb_offset)\\n\",\n",
        "            \"    997         # Remove extra frames from the traceback:\\n\",\n",
        "            \"    998         if tb_offset and tb:\\n\",\n",
        "            \"--> 999             tb = tb.tb_next\\n\",\n",
        "            \"   1000             tb_offset -= 1\\n\",\n",
        "            \"   1001             \\n\",\n",
        "            \"\\n\",\n",
        "            \"/content/Fooocus/entry_with_update.py in <module>\\n\",\n",
        "            \"     44     os.environ[\\\"PYTHONPATH\\\"] = \\\".\\\"\\n\",\n",
        "            \"     45     from modules import shared\\n\",\n",
        "            \"---> 46     from launch import *\\n\",\n",
        "            \"     47     from modules import script_callbacks\\n\",\n",
        "            \"     48     script_callbacks.on_ui_settings()\\n\",\n",
        "            \"\\n\",\n",
        "            \"/content/Fooocus/launch.py in <module>\\n\",\n",
        "            \"    150     from modules import shared as shared\\n\",\n",
        "            \"    151     from modules import ui_extra_networks\\n\",\n",
        "            \"--> 152     from webui import *\\n\",\n",
        "            \"    153     \\n\",\n",
        "            \"    154     # set initial sd_model_checkpoint\\n\",\n",
        "            \"\\n\",\n",
        "            \"/content/Fooocus/webui.py in <module>\\n\",\n",
        "            \"      8     import gradio as gr\\n\",\n",
        "            \"      9     \\n\",\n",
        "            \"---> 10     import modules.async_worker as worker\\n\",\n",
        "            \"     11     from modules import ui, sd_models, shared, images, script_callbacks, sd_samplers, extra_networks, localization\\n\",\n",
        "            \"     12     from modules.call_queue import wrap_queued_call\\n\",\n",
        "            \"\\n\",\n",
        "            \"/content/Fooocus/modules/async_worker.py in <module>\\n\",\n",
        "            \"      1     import gc\\n\",\n",
        "            \"      2     \\n\",\n",
        "            \"----> 3     from extras.inpaint_mask import generate_mask_from_image, SAMOptions\\n\",\n",
        "            \"      4     from extras.roop import roop_process, roop_face_detect\\n\",\n",
        "            \"      5     import modules.shared as shared\\n\",\n",
        "            \"\\n\",\n",
        "            \"/content/Fooocus/extras/inpaint_mask.py in <module>\\n\",\n",
        "            \"      3     from PIL import Image\\n\",\n",
        "            \"      4     import numpy as np\\n\",\n",
        "            \"----> 5     import modules.shared as shared\\n\",\n",
        "            \"      6     import modules.sd_samplers\\n\",\n",
        "            \"      7     \\n\",\n",
        "            \"\\n\",\n",
        "            \"ModuleNotFoundError: No module named 'modules.shared'\\n\"\n",
        "          ]\n",
        "        }\n",
        "      ],\n",
        "      \"source\": [\n",
        "        \"!pip install pygit2==1.15.1\\n\",\n",
        "        \"%cd /content\\n\",\n",
        "        \"!git clone https://github.com/lllyasviel/Fooocus.git\\n\",\n",
        "        \"%cd /content/Fooocus\\n\",\n",
        "        \"!python entry_with_update.py --share --always-high-vram\"\n",
        "      ]\n",
        "    }\n",
        "  ],\n",
        "  \"metadata\": {\n",
        "    \"kernelspec\": {\n",
        "      \"name\": \"python3\",\n",
        "      \"display_name\": \"Python 3\"\n",
        "    },\n",
        "    \"language_info\": {\n",
        "      \"name\": \"python\"\n",
        "    }\n",
        "  },\n",
        "  \"nbformat\": 4,\n",
        "  \"nbformat_minor\": 0\n",
        "}"
      ],
      "metadata": {
        "id": "_GPXyOEG8duy",
        "outputId": "c4b8cea5-8360-4169-faf7-983c5c933c93",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 106
        }
      },
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "error",
          "ename": "IndentationError",
          "evalue": "unindent does not match any outer indentation level (<tokenize>, line 45)",
          "traceback": [
            "\u001b[0;36m  File \u001b[0;32m\"<tokenize>\"\u001b[0;36m, line \u001b[0;32m45\u001b[0m\n\u001b[0;31m    ]\u001b[0m\n\u001b[0m    ^\u001b[0m\n\u001b[0;31mIndentationError\u001b[0m\u001b[0;31m:\u001b[0m unindent does not match any outer indentation level\n"
          ]
        }
      ]
    }
  ],
  "metadata": {
    "accelerator": "GPU",
    "colab": {
      "gpuType": "T4",
      "provenance": []
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}